export const ALLBOOKS = "ALLBOOKS";

export const ALLCLASSES = "ALLCLASSES";

export const GETUNITS = "GETUNITS";

export const GETALLGROUPS = "GETALLGROUPS";

export const GETALLPROFILEDETAILS = "GETALLPROFILEDETAILS";

export const GETALLSTUDENTS = "GETALLSTUDENTS";

export const GETALLEXAMS = "GETALLEXAMS";

export const GETALLLESSONS = "GETALLLESSONS";

export const ALLSTATISTICS = "ALLSTATISTICS";
